version: '3.5'

# Reverse proxy servers for testing.
services:
  caddy:
    image: caddy:2
    depends_on:
      - photoprism
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/development/caddy:/data/caddy/pki/authorities/local
      - ./docker/development/caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  default:
    external:
      name: shared